export default {
  name: 'app',
  state: {
    'data': [{
      'authName': '监控面板',
      'authRoute': '/',
      'authType': 'menu-leaf',
      'children': []
    }, {
      'authName': '停车感知',
      'authRoute': null,
      'authType': 'menu-branch',
      'children': [{
        'authName': '视频设备方案',
        'authRoute': null,
        'authType': 'menu-leaf',
        'children': [{
          'authName': '事件',
          'authRoute': null,
          'authType': 'menu-branch',
          'children': [{
            'authName': '出入场事件',
            'authRoute': '/videoSolution/inOutField',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '事件审核',
            'authRoute': '/videoSolution/evtAudit',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '僵尸车清理',
            'authRoute': '/videoSolution/zombieCarClear',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '自动清洗配置',
            'authRoute': '/videoSolution/autoClearConfig',
            'authType': 'menu-leaf',
            'children': []
          } ]
        }, {
          'authName': '维保',
          'authRoute': null,
          'authType': 'menu-branch',
          'children': [{
            'authName': '图像巡检',
            'authRoute': '/videoSolution/sensingInspection',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '设备状态',
            'authRoute': '/videoSolution/sensingDeviceStatus',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '自动巡检配置',
            'authRoute': '/videoSolution/inspectionParam',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '模拟设备',
            'authRoute': '/videoSolution/simulator',
            'authType': 'menu-leaf',
            'children': []
          } ]
        }, {
          'authName': '数据比对',
          'authRoute': null,
          'authType': 'menu-branch',
          'children': [{
            'authName': '比对报告审核',
            'authRoute': '/comparisonData/auditing',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '抓拍订单查询',
            'authRoute': '/comparisonData/snapOrderSelect',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '停车订单查询',
            'authRoute': '/comparisonData/parkingOrderSelect',
            'authType': 'menu-leaf',
            'children': []
          }]
        }]
      }]
    }, {
      'authName': '违停检测',
      'authRoute': null,
      'authType': 'menu-branch',
      'children': [{
        'authName': '违停球',
        'authRoute': null,
        'authType': 'menu-leaf',
        'children': [{
          'authName': '事件',
          'authRoute': null,
          'authType': 'menu-branch',
          'children': [{
            'authName': '违停审核',
            'authRoute': '/violation/disobeyAudit',
            'authType': 'menu-leaf',
            'children': []
          } ]
        }, {
          'authName': '维保',
          'authRoute': null,
          'authType': 'menu-branch',
          'children': [{
            'authName': '图像巡检',
            'authRoute': '/violation/checkInspection',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '设备状态',
            'authRoute': '/violation/checkDeviceStatus',
            'authType': 'menu-leaf',
            'children': []
          }, {
            'authName': '自动巡检配置',
            'authRoute': '/violation/autoCheckSetting',
            'authType': 'menu-leaf',
            'children': []
          }]
        }]
      }]
    }, {
      'authName': '通用设置',
      'authRoute': null,
      'authType': 'menu-leaf',
      'children': [{
        'authName': '停车点信息',
        'authRoute': '/commonSetting/parkingSpot',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '泊位信息',
        'authRoute': '/commonSetting/berth',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '任务中心',
        'authRoute': '/commonSetting/task',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '事件总汇查询',
        'authRoute': '/commonSetting/evtCollectQuery',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '陌生设备发现',
        'authRoute': '/commonSetting/strangeDevice',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '设备列表',
        'authRoute': '/commonSetting/deviceList',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '泊位对应关系',
        'authRoute': '/commonSetting/deviceNexus',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '分布图',
        'authRoute': '/commonSetting/distribution',
        'authType': 'menu-leaf',
        'children': []
      }]
    }, {
      'authName': '接口监控',
      'authRoute': null,
      'authType': 'menu-leaf',
      'children': [{
        'authName': '设备',
        'authRoute': null,
        'authType': 'menu-branch',
        'children': [{
          'authName': 'API收发日志',
          'authRoute': '/interface/deviceApiLog',
          'authType': 'menu-leaf',
          'children': []
        }, {
          'authName': '接口配置',
          'authRoute': '/interface/apiSetting',
          'authType': 'menu-leaf',
          'children': []
        } ]
      }, {
        'authName': '业务系统',
        'authRoute': null,
        'authType': 'menu-leaf',
        'children': [{
          'authName': '业务系统及协议',
          'authRoute': '/interface/protocol',
          'authType': 'menu-leaf',
          'children': []
        }, {
          'authName': '事件发送监控',
          'authRoute': '/interface/evtSend',
          'authType': 'menu-leaf',
          'children': []
        }, {
          'authName': '接口配置',
          'authRoute': '/interface/interfaceParam',
          'authType': 'menu-leaf',
          'children': []
        }, {
          'authName': 'API收发日志',
          'authRoute': '/interface/businessApiLog',
          'authType': 'menu-leaf',
          'children': []
        }]
      }]
    }, {
      'authName': '系统管理',
      'authRoute': null,
      'authType': 'menu-leaf',
      'children': [{
        'authName': '用户管理',
        'authRoute': '/system/users',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '登录日志',
        'authRoute': '/system/loginLogs',
        'authType': 'menu-leaf',
        'children': []
      }, {
        'authName': '操作日志',
        'authRoute': '/system/operationLogs',
        'authType': 'menu-leaf',
        'children': []
      }]
    }],
    submenuData: {},
    submenuVisible: false
  },
  mutations: {

  }
}
